# Hardware configuration for host: nixos
# Generated by 'nixos-generate-config' - hardware-specific settings only

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # Kernel modules
  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # LUKS encrypted root
  boot.initrd.luks.devices."luks-e82e45af-c075-4c87-b310-c65de4d33949".device = "/dev/disk/by-uuid/e82e45af-c075-4c87-b310-c65de4d33949";

  # Filesystems
  fileSystems."/" = {
    device = "/dev/mapper/luks-e82e45af-c075-4c87-b310-c65de4d33949";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/F3A7-114F";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  # Swap (also encrypted)
  swapDevices = [
    { device = "/dev/mapper/luks-a974ef85-8d19-4ef1-a7e4-cbdd1637fe52"; }
  ];

  # Platform
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
