# Network Configuration
# NetworkManager and related settings

{ config, pkgs, ... }:

{
  # NetworkManager for network management
  networking.networkmanager.enable = true;

  services.openssh = {
    enable = true;

    # Do not open port 22 globally; the firewall rule below limits ingress to
    # the current home IPv4 subnet.
    openFirewall = false;

    settings = {
      AllowUsers = [ "alexloewenthal" ];
      PasswordAuthentication = false;
      KbdInteractiveAuthentication = false;
      PermitRootLogin = "no";
    };
  };

  users.users.alexloewenthal.openssh.authorizedKeys.keys = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGjNrd7F3wfQU3ib54k+xfN/vVlB1QyLMoBK6wrpVcwi Generated By Termius"
  ];

  # The NixOS iptables firewall rejects port 22 by default. Permit it only for
  # clients whose source address is on the home LAN; IPv6 and other interfaces
  # remain closed unless separately allowed elsewhere.
  networking.firewall.extraCommands = ''
    iptables -A nixos-fw -p tcp -s 192.168.1.0/24 --dport 22 -j nixos-fw-accept
  '';
}
